version: '3.8'

services:
  frontend:
    image: 192.168.100.43:5000/hatang.routing.app:0.0.1
    container_name: routing_app
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./.env.local:/app/.env.local:ro
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      start_period: 40s
      retries: 3
    networks:
      - routing_network

networks:
  routing_network:
    driver: bridge
    ipam:
      config:
        - subnet: "173.24.0.0/16"